// Generated by ts-to-zod
import { z } from "zod/v3";

type ObjectSchema = z.ZodObject<any>;
type ZodSchema = z.ZodTypeAny;
type CompletionEvidenceSchema = z.ZodObject<{
    label: z.ZodString;
    url: z.ZodString;
    type: z.ZodString;
}>;

export const columnSchema: ObjectSchema = z.object({
    id: z.number(),
    projectId: z.number(),
    name: z.string(),
    orderIndex: z.number(),
    wipLimit: z.number().nullable()
});

export const progressStateSchema: ZodSchema = z.union([z.literal("todo"), z.literal("in_progress"), z.literal("review"), z.literal("done")]);

export const completionEvidenceItemSchema: CompletionEvidenceSchema = z.object({
    label: z.string().min(1),
    url: z.string().url(),
    type: z.string().min(1)
});

export const ticketRunStatusSchema: ZodSchema = z.union([
    z.literal("planned"),
    z.literal("queued"),
    z.literal("launching"),
    z.literal("running"),
    z.literal("closing_out"),
    z.literal("awaiting_review"),
    z.literal("retry_pending"),
    z.literal("waiting_on_children"),
    z.literal("awaiting_child_confirmation"),
    z.literal("completed"),
    z.literal("failed"),
    z.literal("blocked"),
    z.literal("stopped"),
    z.literal("cancelled")
]);

export const ticketResumeStateSchema: ZodSchema = z.union([
    z.literal("queued"),
    z.literal("running"),
    z.literal("waiting_on_previous_wave"),
    z.literal("awaiting_child_confirmation"),
    z.literal("ready_for_supervisor_review"),
    z.literal("ready_for_retry"),
    z.literal("done"),
    z.literal("blocked"),
    z.literal("cancelled")
]);

export const ticketWorkflowSchema: ObjectSchema = z.object({
    status: z.string(),
    columnId: z.number(),
    progressState: progressStateSchema,
    completedAt: z.string().nullable(),
    completionSummary: z.string().nullable(),
    deploymentProof: z.string().nullable(),
    completionEvidence: z.array(completionEvidenceItemSchema)
});

export const ticketRunArtifactSchema: ObjectSchema = z.object({
    id: z.number(),
    runId: z.number(),
    kind: z.string(),
    label: z.string(),
    url: z.string().url(),
    mimeType: z.string().nullable(),
    createdAt: z.string()
});

export const ticketRunEventSchema: ObjectSchema = z.object({
    id: z.number(),
    runId: z.number(),
    eventType: z.string(),
    message: z.string().nullable(),
    payload: z.record(z.string(), z.unknown()).nullable(),
    createdAt: z.string()
});

export const ticketRunSchema: ObjectSchema = z.object({
    id: z.number(),
    ticketId: z.number(),
    batchId: z.string().nullable(),
    batchItemId: z.number().nullable(),
    handoffId: z.string(),
    threadId: z.string().nullable(),
    executorBackend: z.string().nullable(),
    runStatus: ticketRunStatusSchema,
    resumeState: ticketResumeStateSchema.nullable(),
    bundlePresent: z.boolean(),
    patchApplied: z.boolean(),
    deployUrl: z.string().nullable(),
    terminalReason: z.string().nullable(),
    promptId: z.string().nullable(),
    promptVersion: z.string().nullable(),
    promptManifestVersion: z.string().nullable(),
    runtimeCommitSha: z.string().nullable(),
    validationRequired: z.boolean(),
    validationChecks: z.array(z.record(z.string(), z.unknown())).nullable(),
    createdAt: z.string(),
    startedAt: z.string().nullable(),
    completedAt: z.string().nullable(),
    updatedAt: z.string()
});

export const ticketRunsSummarySchema: ObjectSchema = z.object({
    current: ticketRunSchema.nullable(),
    historyCount: z.number()
});

export const ticketSchema: ObjectSchema = z.object({
    id: z.number(),
    projectId: z.number(),
    columnId: z.number(),
    title: z.string(),
    description: z.string().nullable(),
    estimate: z.number().nullable(),
    status: z.string(),
    progressState: progressStateSchema,
    createdAt: z.string(),
    updatedAt: z.string(),
    completedAt: z.string().nullable(),
    completionSummary: z.string().nullable(),
    deploymentProof: z.string().nullable(),
    completionEvidence: z.array(completionEvidenceItemSchema),
    epicId: z.number().nullable(),
    priority: z.number(),
    workflow: ticketWorkflowSchema,
    runs: ticketRunsSummarySchema
});

export const boardColumnSchema: ObjectSchema = columnSchema.extend({
    tickets: z.array(ticketSchema)
});

export const epicSchema: ObjectSchema = z.object({
    id: z.number(),
    projectId: z.number(),
    name: z.string(),
    description: z.string().nullable(),
    color: z.string().nullable(),
    createdAt: z.string(),
    updatedAt: z.string()
});

export const automationSettingsSchema: ObjectSchema = z.object({
    version: z.number(),
    columnStates: z.record(z.string(), progressStateSchema)
});

export const projectMetricsSchema: ObjectSchema = z.object({
    burnup: z.object({
        dates: z.array(z.string()),
        scope: z.array(z.number()),
        completed: z.array(z.number())
    }),
    burndown: z.object({
        dates: z.array(z.string()),
        remaining: z.array(z.number())
    }),
    velocity: z.object({
        weeks: z.array(z.string()),
        points: z.array(z.number()),
        average: z.number()
    })
});

export const ticketCommentSchema: ObjectSchema = z.object({
    id: z.number(),
    ticketId: z.number(),
    author: z.string().nullable(),
    body: z.string(),
    fileRefs: z.array(z.string()),
    createdAt: z.string()
});

export const docLinkSchema: ObjectSchema = z.object({
    id: z.number(),
    projectId: z.number(),
    ticketId: z.number().nullable(),
    docPath: z.string(),
    docsProjectId: z.string().nullable(),
    linkType: z.string(),
    createdAt: z.string(),
    updatedAt: z.string()
});

export const integrationEventSchema: ObjectSchema = z.object({
    id: z.number(),
    projectId: z.number().nullable(),
    direction: z.union([z.literal("incoming"), z.literal("outgoing")]),
    eventType: z.string(),
    payload: z.record(z.string(), z.unknown()),
    status: z.union([z.literal("pending"), z.literal("processed")]),
    createdAt: z.string(),
    processedAt: z.string().nullable()
});

export const copilotActionTypeSchema: ZodSchema = z.union([z.literal("ticket.create"), z.literal("ticket.update"), z.literal("ticket.delete")]);

export const copilotActionPayloadSchema: ZodSchema = z.record(z.string(), z.unknown());

export const copilotPendingActionSchema: ObjectSchema = z.object({
    id: z.number(),
    projectId: z.number(),
    ticketId: z.number().nullable(),
    actionType: copilotActionTypeSchema,
    summary: z.string(),
    payload: copilotActionPayloadSchema,
    status: z.union([z.literal("pending"), z.literal("approved"), z.literal("rejected")]),
    createdAt: z.string(),
    resolvedAt: z.string().nullable()
});

export const projectSchema: ObjectSchema = z.object({
    id: z.number(),
    key: z.string(),
    name: z.string(),
    description: z.string().nullable(),
    repoPath: z.string().nullable(),
    knowledgeProjectId: z.string().nullable(),
    automationSettings: automationSettingsSchema.nullable(),
    createdAt: z.string(),
    updatedAt: z.string()
});

export const boardSchema: ObjectSchema = z.object({
    project: projectSchema,
    columns: z.array(boardColumnSchema),
    epics: z.array(epicSchema),
    automation: automationSettingsSchema
});

export const ticketBatchItemSchema: ObjectSchema = z.object({
    id: z.number(),
    batchId: z.string(),
    ticketId: z.number(),
    waveIndex: z.number(),
    orderIndex: z.number(),
    planningState: z.string().nullable(),
    blockedByTicketId: z.number().nullable(),
    createdAt: z.string(),
    updatedAt: z.string()
});

export const ticketBatchSchema: ObjectSchema = z.object({
    id: z.string(),
    projectId: z.number(),
    status: z.string(),
    traceId: z.string().nullable(),
    threadId: z.string().nullable(),
    planningPayload: z.record(z.string(), z.unknown()).nullable(),
    createdAt: z.string(),
    updatedAt: z.string(),
    items: z.array(ticketBatchItemSchema)
});

export const stagingLeaseSchema: ObjectSchema = z.object({
    resourceKey: z.string(),
    projectId: z.number(),
    environment: z.literal("staging"),
    active: z.boolean(),
    ownerId: z.string().nullable(),
    ticketId: z.number().nullable(),
    runId: z.number().nullable(),
    candidateRef: z.string().nullable(),
    baselineRef: z.string().nullable(),
    fencingToken: z.number().int().nonnegative(),
    acquiredAt: z.string().nullable(),
    heartbeatAt: z.string().nullable(),
    expiresAt: z.string().nullable(),
    updatedAt: z.string()
});
